stoplist = [
    "_NUM_",
    "§",
    "#",
    "|",
    "hon",
    "mr",
    "sect",
    "x2014",
    "government",
    "right",
    "house",
    "member",
    "gentleman",
    "bill",
    "friend",
    "minister",
    "members",
    "question",
    "secretary",
    "committee",
    "x00a3",
    "0",
    "sir",
    "amendment",
    "lord",
    "clause",
    "prime",
    "parliament",
    "noble",
    "office",
    "speaker",
    "proposed",
    "learned",
    "chancellor",
    "motion",
    "beg",
    "majesty",
    "exchequer",
    "000l",
    "chief",
    "gentlemen",
    "ministry",
    "commissioners",
    "baronet",
    "honourable",
    "ministers",
    "department",
    "colonel",
    "constituency",
    "gent",
    "amendments",
    "lords",
    "attorney",
    "paper",
    "lieutenant",
    "x0021",
    "lieut",
    "mrs",
    "bishops",
    "duke",
    "bills",
    "bishop",
    "commons",
    "marquis",
    "x2013",
    "x00e9",
    "buonapart",
    "clarke",
    "moved",
    "wellesley",
    "highness",
    "melville",
    "castlereagh",
    "oliver",
    "wellington",
    "rose",
    "lordships",
    "earl",
    "act",
    "baroness",
    "debate",
    "viscount",
    "marquess",
    "lady",
    "peers",
    "royal",
    "king",
    "queen",
    "pergami",
    "bergami",
    "brougham",
    "gordon",
    "reverend",
    "governor",
    "russell",
    "lordship",
    "chamber",
    "kimberley",
    "baron",
    "acts",
    "edmunds",
    "normanby",
    "canning",
    "moore",
    "john",
    "eldon",
    "grenville",
    "hawkesbury",
    "gambier",
    "i",
    "me",
    "my",
    "myself",
    "we",
    "our",
    "ours",
    "ourselves",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "her",
    "hers",
    "herself",
    "it",
    "its",
    "itself",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    "what",
    "which",
    "who",
    "whom",
    "this",
    "that",
    "these",
    "those",
    "am",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "doing",
    "a",
    "an",
    "the",
    "and",
    "but",
    "if",
    "or",
    "because",
    "as",
    "until",
    "while",
    "of",
    "at",
    "by",
    "for",
    "with",
    "about",
    "against",
    "between",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "to",
    "from",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "over",
    "under",
    "again",
    "further",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "any",
    "both",
    "each",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "s",
    "t",
    "can",
    "will",
    "just",
    "don",
    "should",
    "now",
    "hon:",
    "mr:",
    "sect:",
    "hon",
    "mr",
    "sect",
    "hon.",
    "mr.",
    "sect.",
    "x2014",
    "government",
    "right",
    "house",
    "member",
    "gentleman",
    "bill",
    "friend",
    "minister",
    "members",
    "question",
    "secretary",
    "committee",
    "sir",
    "amendment",
    "lord",
    "clause",
    "prime",
    "parliament",
    "noble",
    "office",
    "speaker",
    "proposed",
    "learned",
    "chancellor",
    "motion",
    "beg",
    "majesty",
    "exchequer",
    "chief",
    "gentlemen",
    "ministry",
    "commissioners",
    "baronet",
    "honourable",
    "ministers",
    "department",
    "colonel",
    "constituency",
    "gent",
    "amendments",
    "lords",
    "attorney",
    "paper",
    "lieutenant",
    "lieut",
    "mrs",
    "bishops",
    "duke",
    "bills",
    "bishop",
    "commons",
    "marquis",
    "x2013",
    "x00e9",
    "buonapart",
    "clarke",
    "moved",
    "wellesley",
    "highness",
    "melville",
    "castlereagh",
    "oliver",
    "wellington",
    "rose",
    "lordships",
    "earl",
    "act",
    "baroness",
    "debate",
    "viscount",
    "marquess",
    "lady",
    "peers",
    "royal",
    "king",
    "queen",
    "pergami",
    "bergami",
    "brougham",
    "gordon",
    "reverend",
    "governor",
    "russell",
    "lordship",
    "chamber",
    "kimberley",
    "baron",
    "acts",
    "edmunds",
    "normanby",
    "canning",
    "moore",
    "john",
    "eldon",
    "grenville",
    "hawkesbury",
    "gambier",
    "i",
    "me",
    "my",
    "myself",
    "we",
    "our",
    "ours",
    "ourselves",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "her",
    "hers",
    "herself",
    "it",
    "its",
    "itself",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    "what",
    "which",
    "who",
    "whom",
    "this",
    "that",
    "these",
    "those",
    "am",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "doing",
    "a",
    "an",
    "the",
    "and",
    "but",
    "if",
    "or",
    "because",
    "as",
    "until",
    "while",
    "of",
    "at",
    "by",
    "for",
    "with",
    "about",
    "against",
    "between",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "to",
    "from",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "over",
    "under",
    "again",
    "further",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "any",
    "both",
    "each",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "s",
    "t",
    "can",
    "will",
    "just",
    "don",
    "should",
    "now",
    "hon:",
    "mr:",
    "sect:",
    "hon",
    "mr",
    "sect",
    "hon.",
    "mr.",
    "sect.",
    "x2014",
    "government",
    "right",
    "house",
    "member",
    "gentleman",
    "bill",
    "friend",
    "minister",
    "members",
    "question",
    "secretary",
    "committee",
    "sir",
    "amendment",
    "lord",
    "clause",
    "prime",
    "parliament",
    "noble",
    "office",
    "speaker",
    "proposed",
    "learned",
    "chancellor",
    "motion",
    "beg",
    "majesty",
    "exchequer",
    "chief",
    "gentlemen",
    "ministry",
    "commissioners",
    "baronet",
    "honourable",
    "ministers",
    "department",
    "colonel",
    "constituency",
    "gent",
    "amendments",
    "lords",
    "attorney",
    "paper",
    "lieutenant",
    "lieut",
    "mrs",
    "bishops",
    "duke",
    "bills",
    "bishop",
    "commons",
    "marquis",
    "x2013",
    "x00e9",
    "buonapart",
    "clarke",
    "moved",
    "wellesley",
    "highness",
    "melville",
    "castlereagh",
    "oliver",
    "wellington",
    "rose",
    "lordships",
    "earl",
    "act",
    "baroness",
    "debate",
    "viscount",
    "marquess",
    "lady",
    "peers",
    "royal",
    "king",
    "queen",
    "pergami",
    "bergami",
    "brougham",
    "gordon",
    "reverend",
    "governor",
    "russell",
    "lordship",
    "chamber",
    "kimberley",
    "baron",
    "acts",
    "edmunds",
    "normanby",
    "canning",
    "moore",
    "john",
    "eldon",
    "grenville",
    "hawkesbury",
    "gambier",
    "i",
    "me",
    "my",
    "myself",
    "we",
    "our",
    "ours",
    "ourselves",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "her",
    "hers",
    "herself",
    "it",
    "its",
    "itself",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    "what",
    "which",
    "who",
    "whom",
    "this",
    "that",
    "these",
    "those",
    "am",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "doing",
    "a",
    "an",
    "the",
    "and",
    "but",
    "if",
    "or",
    "because",
    "as",
    "until",
    "while",
    "of",
    "at",
    "by",
    "for",
    "with",
    "about",
    "against",
    "between",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "to",
    "from",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "over",
    "under",
    "again",
    "further",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "any",
    "both",
    "each",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "s",
    "t",
    "can",
    "will",
    "just",
    "don",
    "should",
    "now",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "rt",
    "ought",
    "should",
    "would",
    "could",
    "may",
    "might",
    "shall",
    "will","0o", "0s", "3a", "3b", "3d", "6b", "6o", "a", "a1", "a2", "a3", "a4", "ab", "able", "about", "above", "abst", "ac", "accordance", "according", "accordingly", "across", "act", "actually", "ad", "added", "adj", "ae", "af", "affected", "affecting", "affects", "after", "afterwards", "ag", "again", "against", "ah", "ain", "ain't", "aj", "al", "all", "allow", "allows", "almost", "alone", "along", "already", "also", "although", "always", "am", "among", "amongst", "amoungst", "amount", "an", "and", "announce", "another", "any", "anybody", "anyhow", "anymore", "anyone", "anything", "anyway", "anyways", "anywhere", "ao", "ap", "apart", "apparently", "appear", "appreciate", "appropriate", "approximately", "ar", "are", "aren", "arent", "aren't", "arise", "around", "as", "a's", "aside", "ask", "asking", "associated", "at", "au", "auth", "av", "available", "aw", "away", "awfully", "ax", "ay", "az", "b", "b1", "b2", "b3", "ba", "back", "bc", "bd", "be", "became", "because", "become", "becomes", "becoming", "been", "before", "beforehand", "begin", "beginning", "beginnings", "begins", "behind", "being", "believe", "below", "beside", "besides", "best", "better", "between", "beyond", "bi", "bill", "biol", "bj", "bk", "bl", "bn", "both", "bottom", "bp", "br", "brief", "briefly", "bs", "bt", "bu", "but", "bx", "by", "c", "c1", "c2", "c3", "ca", "call", "came", "can", "cannot", "cant", "can't", "cause", "causes", "cc", "cd", "ce", "certain", "certainly", "cf", "cg", "ch", "changes", "ci", "cit", "cj", "cl", "clearly", "cm", "c'mon", "cn", "co", "com", "come", "comes", "con", "concerning", "consequently", "consider", "considering", "contain", "containing", "contains", "corresponding", "could", "couldn", "couldnt", "couldn't", "course", "cp", "cq", "cr", "cry", "cs", "c's", "ct", "cu", "currently", "cv", "cx", "cy", "cz", "d", "d2", "da", "date", "dc", "dd", "de", "definitely", "describe", "described", "despite", "detail", "df", "di", "did", "didn", "didn't", "different", "dj", "dk", "dl", "do", "does", "doesn", "doesn't", "doing", "don", "done", "don't", "down", "downwards", "dp", "dr", "ds", "dt", "du", "due", "during", "dx", "dy", "e", "e2", "e3", "ea", "each", "ec", "ed", "edu", "ee", "ef", "effect", "eg", "ei", "eight", "eighty", "either", "ej", "el", "eleven", "else", "elsewhere", "em", "empty", "en", "end", "ending", "enough", "entirely", "eo", "ep", "eq", "er", "es", "especially", "est", "et", "et-al", "etc", "eu", "ev", "even", "ever", "every", "everybody", "everyone", "everything", "everywhere", "ex", "exactly", "example", "except", "ey", "f", "f2", "fa", "far", "fc", "few", "ff", "fi", "fifteen", "fifth", "fify", "fill", "find", "fire", "first", "five", "fix", "fj", "fl", "fn", "fo", "followed", "following", "follows", "for", "former", "formerly", "forth", "forty", "found", "four", "fr", "from", "front", "fs", "ft", "fu", "full", "further", "furthermore", "fy", "g", "ga", "gave", "ge", "get", "gets", "getting", "gi", "give", "given", "gives", "giving", "gj", "gl", "go", "goes", "going", "gone", "got", "gotten", "gr", "greetings", "gs", "gy", "h", "h2", "h3", "had", "hadn", "hadn't", "happens", "hardly", "has", "hasn", "hasnt", "hasn't", "have", "haven", "haven't", "having", "he", "hed", "he'd", "he'll", "hello", "help", "hence", "her", "here", "hereafter", "hereby", "herein", "heres", "here's", "hereupon", "hers", "herself", "hes", "he's", "hh", "hi", "hid", "him", "himself", "his", "hither", "hj", "ho", "home", "hopefully", "how", "howbeit", "however", "how's", "hr", "hs", "http", "hu", "hundred", "hy", "i", "i2", "i3", "i4", "i6", "i7", "i8", "ia", "ib", "ibid", "ic", "id", "i'd", "ie", "if", "ig", "ignored", "ih", "ii", "ij", "il", "i'll", "im", "i'm", "immediate", "immediately", "importance", "important", "in", "inasmuch", "inc", "indeed", "index", "indicate", "indicated", "indicates", "information", "inner", "insofar", "instead", "interest", "into", "invention", "inward", "io", "ip", "iq", "ir", "is", "isn", "isn't", "it", "itd", "it'd", "it'll", "its", "it's", "itself", "iv", "i've", "ix", "iy", "iz", "j", "jj", "jr", "js", "jt", "ju", "just", "k", "ke", "keep", "keeps", "kept", "kg", "kj", "km", "know", "known", "knows", "ko", "l", "l2", "la", "largely", "last", "lately", "later", "latter", "latterly", "lb", "lc", "le", "least", "les", "less", "lest", "let", "lets", "let's", "lf", "like", "liked", "likely", "line", "little", "lj", "ll", "ll", "ln", "lo", "look", "looking", "looks", "los", "lr", "ls", "lt", "ltd", "m", "m2", "ma", "made", "mainly", "make", "makes", "many", "may", "maybe", "me", "mean", "means", "meantime", "meanwhile", "merely", "mg", "might", "mightn", "mightn't", "mill", "million", "mine", "miss", "ml", "mn", "mo", "more", "moreover", "most", "mostly", "move", "mr", "mrs", "ms", "mt", "mu", "much", "mug", "must", "mustn", "mustn't", "my", "myself", "n", "n2", "na", "name", "namely", "nay", "nc", "nd", "ne", "near", "nearly", "necessarily", "necessary", "need", "needn", "needn't", "needs", "neither", "never", "nevertheless", "new", "next", "ng", "ni", "nine", "ninety", "nj", "nl", "nn", "no", "nobody", "non", "none", "nonetheless", "noone", "nor", "normally", "nos", "not", "noted", "nothing", "novel", "now", "nowhere", "nr", "ns", "nt", "ny", "o", "oa", "ob", "obtain", "obtained", "obviously", "oc", "od", "of", "off", "often", "og", "oh", "oi", "oj", "ok", "okay", "ol", "old", "om", "omitted", "on", "once", "one", "ones", "only", "onto", "oo", "op", "oq", "or", "ord", "os", "ot", "other", "others", "otherwise", "ou", "ought", "our", "ours", "ourselves", "out", "outside", "over", "overall", "ow", "owing", "own", "ox", "oz", "p", "p1", "p2", "p3", "page", "pagecount", "pages", "par", "part", "particular", "particularly", "pas", "past", "pc", "pd", "pe", "per", "perhaps", "pf", "ph", "pi", "pj", "pk", "pl", "placed", "please", "plus", "pm", "pn", "po", "poorly", "possible", "possibly", "potentially", "pp", "pq", "pr", "predominantly", "present", "presumably", "previously", "primarily", "probably", "promptly", "proud", "provides", "ps", "pt", "pu", "put", "py", "q", "qj", "qu", "que", "quickly", "quite", "qv", "r", "r2", "ra", "ran", "rather", "rc", "rd", "re", "readily", "really", "reasonably", "recent", "recently", "ref", "refs", "regarding", "regardless", "regards", "related", "relatively", "research", "research-articl", "respectively", "resulted", "resulting", "results", "rf", "rh", "ri", "right", "rj", "rl", "rm", "rn", "ro", "rq", "rr", "rs", "rt", "ru", "run", "rv", "ry", "s", "s2", "sa", "said", "same", "saw", "say", "saying", "says", "sc", "sd", "se", "sec", "second", "secondly", "section", "see", "seeing", "seem", "seemed", "seeming", "seems", "seen", "self", "selves", "sensible", "sent", "serious", "seriously", "seven", "several", "sf", "shall", "shan", "shan't", "she", "shed", "she'd", "she'll", "shes", "she's", "should", "shouldn", "shouldn't", "should've", "show", "showed", "shown", "showns", "shows", "si", "side", "significant", "significantly", "similar", "similarly", "since", "sincere", "six", "sixty", "sj", "sl", "slightly", "sm", "sn", "so", "some", "somebody", "somehow", "someone", "somethan", "something", "sometime", "sometimes", "somewhat", "somewhere", "soon", "sorry", "sp", "specifically", "specified", "specify", "specifying", "sq", "sr", "ss", "st", "still", "stop", "strongly", "sub", "substantially", "successfully", "such", "sufficiently", "suggest", "sup", "sure", "sy", "system", "sz", "t", "t1", "t2", "t3", "take", "taken", "taking", "tb", "tc", "td", "te", "tell", "ten", "tends", "tf", "th", "than", "thank", "thanks", "thanx", "that", "that'll", "thats", "that's", "that've", "the", "their", "theirs", "them", "themselves", "then", "thence", "there", "thereafter", "thereby", "thered", "therefore", "therein", "there'll", "thereof", "therere", "theres", "there's", "thereto", "thereupon", "there've", "these", "they", "theyd", "they'd", "they'll", "theyre", "they're", "they've", "thickv", "thin", "think", "third", "this", "thorough", "thoroughly", "those", "thou", "though", "thoughh", "thousand", "three", "throug", "through", "throughout", "thru", "thus", "ti", "til", "tip", "tj", "tl", "tm", "tn", "to", "together", "too", "took", "top", "toward", "towards", "tp", "tq", "tr", "tried", "tries", "truly", "try", "trying", "ts", "t's", "tt", "tv", "twelve", "twenty", "twice", "two", "tx", "u", "u201d", "ue", "ui", "uj", "uk", "um", "un", "under", "unfortunately", "unless", "unlike", "unlikely", "until", "unto", "uo", "up", "upon", "ups", "ur", "us", "use", "used", "useful", "usefully", "usefulness", "uses", "using", "usually", "ut", "v", "va", "value", "various", "vd", "ve", "ve", "very", "via", "viz", "vj", "vo", "vol", "vols", "volumtype", "vq", "vs", "vt", "vu", "w", "wa", "want", "wants", "was", "wasn", "wasnt", "wasn't", "way", "we", "wed", "we'd", "welcome", "well", "we'll", "well-b", "went", "were", "we're", "weren", "werent", "weren't", "we've", "what", "whatever", "what'll", "whats", "what's", "when", "whence", "whenever", "when's", "where", "whereafter", "whereas", "whereby", "wherein", "wheres", "where's", "whereupon", "wherever", "whether", "which", "while", "whim", "whither", "who", "whod", "whoever", "whole", "who'll", "whom", "whomever", "whos", "who's", "whose", "why", "why's", "wi", "widely", "will", "willing", "wish", "with", "within", "without", "wo", "won", "wonder", "wont", "won't", "words", "world", "would", "wouldn", "wouldnt", "wouldn't", "www", "x", "x1", "x2", "x3", "xf", "xi", "xj", "xk", "xl", "xn", "xo", "xs", "xt", "xv", "xx", "y", "y2", "yes", "yet", "yj", "yl", "you", "youd", "you'd", "you'll", "your", "youre", "you're", "yours", "yourself", "yourselves", "you've", "yr", "ys", "yt", "z", "zero", "zi", "zz"]

periods = [ 
    {"title": "Henry Addington", "desc": "Tory", "type" : "PM_TERM", "dateFrom" : "1803-01-01", "dateTo" : "1804-05-10"},
    {"title": "William Pitt - The Younger", "desc": "Tory", "type" : "PM_TERM", "dateFrom" : "1804-05-10", "dateTo" : "1806-01-23"},
    {"title": "William Wyndham Grenville, Lord Grenville", "desc": "Whig", "type" : "PM_TERM", "dateFrom" : "1806-02-11", "dateTo" : "1807-03-25"},
    {"title": "William Bentinck, Duke of Portland", "desc": "Tory", "type" : "PM_TERM", "dateFrom" : "1808-03-31", "dateTo" : "1809-10-04"},
    {"title": "Spencer Perceval", "desc": "Tory", "type" : "PM_TERM", "dateFrom" : "1809-10-04", "dateTo" : "1812-05-11"},
    {"title": "Robert Banks Jenkinson, 2nd Earl of Liverpool", "desc": "Tory", "type" : "PM_TERM", "dateFrom" : "1812-06-08", "dateTo" : "1827-04-09"},
    {"title": "George Canning", "desc": "Tory", "type" : "PM_TERM", "dateFrom" : "1827-04-12", "dateTo" : "1827-08-08"},
    {"title": "Frederick Robinson, Viscount Goderich", "desc": "Tory", "type" : "PM_TERM", "dateFrom" : "1827-08-31", "dateTo" : "1828-01-08"},
    {"title": "Arthur Wellesley, 1st Duke of Wellington", "desc": "Tory", "type" : "PM_TERM", "dateFrom" : "1828-01-22", "dateTo" : "1830-11-16"},
    {"title": "Charles Grey", "desc": "Whig", "type" : "PM_TERM", "dateFrom" : "1830-11-22", "dateTo" : "1834-07-09"},
    {"title": "William Lamb, 2nd Viscount Melbourne", "desc": "Whig", "type" : "PM_TERM", "dateFrom" : "1834-07-16", "dateTo" : "1834-11-14"},
    {"title": "Arthur Wellesley, 1st Duke of Wellington", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1834-11-17", "dateTo" : "1834-12-09"},
    {"title": "Robert Peel", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1834-12-10", "dateTo" : "1835-04-08"},
    {"title": "William Lamb, 2nd Viscount Melbourne", "desc": "Whig", "type" : "PM_TERM", "dateFrom" : "1835-04-18", "dateTo" : "1841-08-30"},
    {"title": "Robert Peel", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1841-08-30", "dateTo" : "1846-06-29"},
    {"title": "John Russell", "desc": "Whig", "type" : "PM_TERM", "dateFrom" : "1846-06-30", "dateTo" : "1852-02-21"},
    {"title": "Edward Smith Stanley, 14th Earl of Derby", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1852-02-23", "dateTo" : "1852-12-17"},
    {"title": "George Hamilton Gordon, 4th Earl of Aberdeen", "desc": "Coalition", "type" : "PM_TERM", "dateFrom" : "1852-12-19", "dateTo" : "1855-01-30"},
    {"title": "Henry John Temple, 3rd Viscount Palmerston", "desc": "Whig", "type" : "PM_TERM", "dateFrom" : "1855-02-06", "dateTo" : "1858-02-19"},
    {"title": "Edward Smith Stanley, 14th Earl of Derby", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1858-02-20", "dateTo" : "1859-06-11"},
    {"title": "Henry John Temple, 3rd Viscount Palmerston", "desc": "Liberal", "type" : "PM_TERM", "dateFrom" : "1859-06-12", "dateTo" : "1865-10-18"},
    {"title": "John Russell", "desc": "Liberal", "type" : "PM_TERM", "dateFrom" : "1865-10-29", "dateTo" : "1866-06-26"},
    {"title": "Edward Smith Stanley, 14th Earl of Derby", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1866-06-28", "dateTo" : "1868-02-25"},
    {"title": "Benjamin Disreali", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1868-02-27", "dateTo" : "1868-12-01"},
    {"title": "William Ewart Gladstone", "desc": "Liberal", "type" : "PM_TERM", "dateFrom" : "1868-12-03", "dateTo" : "1874-02-17"},
    {"title": "Benjamin Disreali", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1874-02-20", "dateTo" : "1880-04-21"},
    {"title": "William Ewart Gladstone", "desc": "Liberal", "type" : "PM_TERM", "dateFrom" : "1880-04-23", "dateTo" : "1885-06-09"},
    {"title": "Robert Gascoyne-Cecil 3rd Marquess of Salisbury", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1885-06-23", "dateTo" : "1886-01-28"},
    {"title": "William Ewart Gladstone", "desc": "Liberal", "type" : "PM_TERM", "dateFrom" : "1886-02-01", "dateTo" : "1886-07-20"},
    {"title": "Robert Gascoyne-Cecil 3rd Marquess of Salisbury", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1886-07-25", "dateTo" : "1892-08-11"},
    {"title": "William Ewart Gladstone", "desc": "Liberal", "type" : "PM_TERM", "dateFrom" : "1892-08-15", "dateTo" : "1894-03-02"},
    {"title": "Archibald Primrose 5th Earl of Rosebery", "desc": "Liberal", "type" : "PM_TERM", "dateFrom" : "1894-03-05", "dateTo" : "1895-06-22"},
    {"title": "Robert Gascoyne-Cecil 3rd Marquess of Salisbury", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1895-06-25", "dateTo" : "1902-07-11"},
    {"title": "Arthur James Balfour", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1902-07-12", "dateTo" : "1905-12-04"},
    {"title": "Henry Campbell-Bannerman", "desc": "Liberal", "type" : "PM_TERM", "dateFrom" : "1905-12-05", "dateTo" : "1908-04-05"},
    {"title": "Herbert Henry Asquith", "desc": "Liberal", "type" : "PM_TERM", "dateFrom" : "1908-04-05", "dateTo" : "1916-12-05"},
    {"title": "David Lloyd George", "desc": "Coalition", "type" : "PM_TERM", "dateFrom" : "1916-12-06", "dateTo" : "1922-10-19"},
    {"title": "Andrew Bonar Law", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1922-10-23", "dateTo" : "1923-05-20"},
    {"title": "Stanley Baldwin", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1923-05-22", "dateTo" : "1924-01-22"},
    {"title": "James Ramsay MacDonald", "desc": "Labour", "type" : "PM_TERM", "dateFrom" : "1924-01-22", "dateTo" : "1924-11-04"},
    {"title": "Stanley Baldwin", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1924-11-04", "dateTo" : "1929-06-05"},
    {"title": "James Ramsay MacDonald", "desc": "Labour", "type" : "PM_TERM", "dateFrom" : "1929-06-05", "dateTo" : "1935-06-07"},
    {"title": "Stanley Baldwin", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1935-06-07", "dateTo" : "1937-05-28"},
    {"title": "Neville Chamberlain", "desc": "Coalition", "type" : "PM_TERM", "dateFrom" : "1937-05-28", "dateTo" : "1940-05-10"},
    {"title": "Winston Churchill", "desc": "Coalition", "type" : "PM_TERM", "dateFrom" : "1940-05-10", "dateTo" : "1945-07-26"},
    {"title": "Clement Attlee", "desc": "Labour", "type" : "PM_TERM", "dateFrom" : "1945-07-26", "dateTo" : "1951-10-26"},
    {"title": "Winston Churchill", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1951-10-26", "dateTo" : "1955-04-06"},
    {"title": "Anthony Eden", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1955-04-06", "dateTo" : "1957-01-10"},
    {"title": "Harold Macmillan", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1957-01-10", "dateTo" : "1963-10-19"},
    {"title": "Alec Douglas-Home", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1963-10-19", "dateTo" : "1964-10-16"},
    {"title": "Harold Wilson", "desc": "Labour", "type" : "PM_TERM", "dateFrom" : "1964-10-16", "dateTo" : "1970-06-19"},
    {"title": "Edward Heath", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1970-06-19", "dateTo" : "1974-03-04"},
    {"title": "Harold Wilson", "desc": "Labour", "type" : "PM_TERM", "dateFrom" : "1974-03-04", "dateTo" : "1976-04-05"},
    {"title": "James Callaghan", "desc": "Labour", "type" : "PM_TERM", "dateFrom" : "1976-04-05", "dateTo" : "1979-05-04"},
    {"title": "Margaret Thatcher", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1979-05-04", "dateTo" : "1990-11-28"},
    {"title": "John Major", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "1990-11-28", "dateTo" : "1997-05-02"},
    {"title": "Tony Blair", "desc": "Labour", "type" : "PM_TERM", "dateFrom" : "1997-05-02", "dateTo" : "2007-06-27"},
    {"title": "Gordon Brown", "desc": "Labour", "type" : "PM_TERM", "dateFrom" : "2007-06-27", "dateTo" : "2010-05-11"},
    {"title": "David Cameron", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "2010-05-11", "dateTo" : "2016-07-13"},
    {"title": "Theresa May", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "2016-07-13", "dateTo" : "2019-09-24"},
    {"title": "Boris Johnson", "desc": "Conservative", "type" : "PM_TERM", "dateFrom" : "2019-09-24", "dateTo" : "2022-01-05"},


    {"title": "Henry Addington I", "desc": "Tory", "type" : "PM_SESSION", "dateFrom" : "1803-01-01", "dateTo" : "1804-05-10"},
    {"title": "William Pitt - The Younger I", "desc": "Tory", "type" : "PM_SESSION", "dateFrom" : "1804-05-10", "dateTo" : "1806-01-23"},
    {"title": "William Wyndham Grenville, Lord Grenville I", "desc": "Tory", "type" : "PM_SESSION", "dateFrom" : "1806-02-11", "dateTo" : "1807-03-25"},
    {"title": "William Bentinck, Duke of Portland I", "desc": "Tory", "type" : "PM_SESSION", "dateFrom" : "1807-03-31", "dateTo" : "1809-10-04"},
    {"title": "Spencer Perceval I", "desc": "Tory", "type" : "PM_SESSION", "dateFrom" : "1809-10-04", "dateTo" : "1812-05-11"},
    {"title": "Robert Banks Jenkinson, 2nd Earl of Liverpool I", "desc": "Tory", "type" : "PM_SESSION", "dateFrom" : "1812-06-08", "dateTo" : "1827-04-09"},
    {"title": "George Canning I", "desc": "Tory", "type" : "PM_SESSION", "dateFrom" : "1827-04-12", "dateTo" : "1827-08-08"},
    {"title": "Frederick Robinson, Viscount Goderich I", "desc": "Tory", "type" : "PM_SESSION", "dateFrom" : "1827-08-31", "dateTo" : "1828-01-08"},
    {"title": "Arthur Wellesley, 1st Duke of Wellington I", "desc": "Tory", "type" : "PM_SESSION", "dateFrom" : "1828-01-22", "dateTo" : "1830-11-16"},
    {"title": "Charles Grey I", "desc": "Whig", "type" : "PM_SESSION", "dateFrom" : "1830-11-22", "dateTo" : "1834-07-09"},
    {"title": "William Lamb, 2nd Viscount Melbourne I", "desc": "Whig", "type" : "PM_SESSION", "dateFrom" : "1834-07-16", "dateTo" : "1834-11-14"},
    {"title": "Arthur Wellesley, 1st Duke of Wellington II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1834-11-17", "dateTo" : "1834-12-09"},
    {"title": "Robert Peel I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1834-12-10", "dateTo" : "1835-04-08"},
    {"title": "William Lamb, 2nd Viscount Melbourne II", "desc": "Whig", "type" : "PM_SESSION", "dateFrom" : "1835-04-18", "dateTo" : "1841-08-30"},
    {"title": "Robert Peel II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1841-08-30", "dateTo" : "1846-06-29"},
    {"title": "John Russell I", "desc": "Whig", "type" : "PM_SESSION", "dateFrom" : "1846-06-30", "dateTo" : "1852-02-21"},
    {"title": "Edward Smith Stanley, 14th Earl of Derby I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1852-02-23", "dateTo" : "1852-12-17"},
    {"title": "George Hamilton Gordon, 4th Earl of Aberdeen I", "desc": "Coalition", "type" : "PM_SESSION", "dateFrom" : "1852-12-19", "dateTo" : "1855-01-30"},
    {"title": "Henry John Temple, 3rd Viscount Palmerston I", "desc": "Whig", "type" : "PM_SESSION", "dateFrom" : "1855-02-06", "dateTo" : "1858-02-19"},
    {"title": "Edward Smith Stanley, 14th Earl of Derby II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1858-02-20", "dateTo" : "1859-06-11"},
    {"title": "Henry John Temple, 3rd Viscount Palmerston II", "desc": "Liberal", "type" : "PM_SESSION", "dateFrom" : "1859-06-12", "dateTo" : "1865-10-18"},
    {"title": "John Russell II", "desc": "Liberal", "type" : "PM_SESSION", "dateFrom" : "1865-10-29", "dateTo" : "1866-06-26"},
    {"title": "Edward Smith Stanley, 14th Earl of Derby III", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1866-06-28", "dateTo" : "1868-02-25"},
    {"title": "Benjamin Disreali I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1868-02-27", "dateTo" : "1868-12-01"},
    {"title": "William Ewart Gladstone I", "desc": "Liberal", "type" : "PM_SESSION", "dateFrom" : "1868-12-03", "dateTo" : "1874-02-17"},
    {"title": "Benjamin Disreali II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1874-02-20", "dateTo" : "1880-04-21"},
    {"title": "William Ewart Gladstone II", "desc": "Liberal", "type" : "PM_SESSION", "dateFrom" : "1880-04-23", "dateTo" : "1885-06-09"},
    {"title": "Robert Gascoyne-Cecil 3rd Marquess of Salisbury I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1885-06-23", "dateTo" : "1886-01-28"},
    {"title": "William Ewart Gladstone III", "desc": "Liberal", "type" : "PM_SESSION", "dateFrom" : "1886-02-01", "dateTo" : "1886-07-20"},
    {"title": "Robert Gascoyne-Cecil 3rd Marquess of Salisbury II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1886-07-25", "dateTo" : "1892-08-11"},
    {"title": "William Ewart Gladstone IV", "desc": "Liberal", "type" : "PM_SESSION", "dateFrom" : "1892-08-15", "dateTo" : "1894-03-02"},
    {"title": "Archibald Primrose 5th Earl of Rosebery I", "desc": "Liberal", "type" : "PM_SESSION", "dateFrom" : "1894-03-05", "dateTo" : "1895-06-22"},
    {"title": "Robert Gascoyne-Cecil 3rd Marquess of Salisbury III", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1895-06-25", "dateTo" : "1900-10-24"},
    {"title": "Robert Gascoyne-Cecil 3rd Marquess of Salisbury IV", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1900-10-24", "dateTo" : "1902-07-11"},
    {"title": "Arthur James Balfour I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1902-07-12", "dateTo" : "1905-12-04"},
    {"title": "Henry Campbell-Bannerman I", "desc": "Liberal", "type" : "PM_SESSION", "dateFrom" : "1905-12-05", "dateTo" : "1908-04-05"},
    {"title": "Herbert Henry Asquith I", "desc": "Liberal", "type" : "PM_SESSION", "dateFrom" : "1908-04-05", "dateTo" : "1910-02-09"},
    {"title": "Herbert Henry Asquith II", "desc": "Liberal", "type" : "PM_SESSION", "dateFrom" : "1910-02-09", "dateTo" : "1910-12-19"},
    {"title": "Herbert Henry Asquith III", "desc": "Liberal", "type" : "PM_SESSION", "dateFrom" : "1910-12-19", "dateTo" : "1915-05-25"},
    {"title": "Herbert Henry Asquith VI", "desc": "Coalition", "type" : "PM_SESSION", "dateFrom" : "1915-05-25", "dateTo" : "1916-12-05"},
    {"title": "David Lloyd George I", "desc": "Coalition", "type" : "PM_SESSION", "dateFrom" : "1916-12-06", "dateTo" : "1918-12-14"},
    {"title": "David Lloyd George II", "desc": "Coalition", "type" : "PM_SESSION", "dateFrom" : "1918-12-14", "dateTo" : "1922-10-19"},
    {"title": "Andrew Bonar Law I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1922-10-23", "dateTo" : "1923-05-20"},
    {"title": "Stanley Baldwin I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1923-05-22", "dateTo" : "1924-01-22"},
    {"title": "James Ramsay MacDonald I", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1924-01-22", "dateTo" : "1924-11-04"},
    {"title": "Stanley Baldwin II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1924-11-04", "dateTo" : "1929-06-05"},
    {"title": "James Ramsay MacDonald II", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1929-06-05", "dateTo" : "1931-08-24"},
    {"title": "James Ramsay MacDonald III", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1931-08-24", "dateTo" : "1931-10-27"},
    {"title": "James Ramsay MacDonald IV", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1931-10-27", "dateTo" : "1935-06-07"},
    {"title": "Stanley Baldwin III", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1935-06-07", "dateTo" : "1935-11-14"},
    {"title": "Stanley Baldwin IV", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1935-11-14", "dateTo" : "1937-05-28"},
    {"title": "Neville Chamberlain I", "desc": "Coalition", "type" : "PM_SESSION", "dateFrom" : "1937-05-28", "dateTo" : "1940-05-10"},
    {"title": "Winston Churchill I", "desc": "Coalition", "type" : "PM_SESSION", "dateFrom" : "1940-05-10", "dateTo" : "1945-05-23"},
    {"title": "Winston Churchill II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1945-05-23", "dateTo" : "1945-07-26"},
    {"title": "Clement Attlee I", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1945-07-26", "dateTo" : "1950-05-23"},
    {"title": "Clement Attlee II", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1950-05-23", "dateTo" : "1951-10-26"},
    {"title": "Winston Churchill III", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1951-10-26", "dateTo" : "1955-04-06"},
    {"title": "Anthony Eden I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1955-04-06", "dateTo" : "1957-01-10"},
    {"title": "Harold Macmillan I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1957-01-10", "dateTo" : "1959-10-08"},
    {"title": "Harold Macmillan II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1959-10-08", "dateTo" : "1963-10-19"},
    {"title": "Alec Douglas-Home I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1963-10-19", "dateTo" : "1964-10-16"},
    {"title": "Harold Wilson I", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1964-10-16", "dateTo" : "1966-03-31"},
    {"title": "Harold Wilson II", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1966-03-31", "dateTo" : "1970-06-19"},
    {"title": "Edward Heath I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1970-06-19", "dateTo" : "1974-03-04"},
    {"title": "Harold Wilson III", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1974-03-04", "dateTo" : "1974-10-10"},
    {"title": "Harold Wilson IV", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1974-10-10", "dateTo" : "1976-04-05"},
    {"title": "James Callaghan I", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1976-04-05", "dateTo" : "1979-05-04"},
    {"title": "Margaret Thatcher I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1979-05-04", "dateTo" : "1983-06-09"},
    {"title": "Margaret Thatcher II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1983-06-09", "dateTo" : "1987-06-11"},
    {"title": "Margaret Thatcher III", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1987-06-11", "dateTo" : "1990-11-28"},
    {"title": "John Major I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1990-11-28", "dateTo" : "1992-04-09"},
    {"title": "John Major II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "1992-04-09", "dateTo" : "1997-05-02"},
    {"title": "Tony Blair I", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "1997-05-02", "dateTo" : "2001-06-07"},
    {"title": "Tony Blair II", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "2001-06-07", "dateTo" : "2005-05-05"},
    {"title": "Tony Blair III", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "2005-05-05", "dateTo" : "2007-06-27"},
    {"title": "Gordon Brown I", "desc": "Labour", "type" : "PM_SESSION", "dateFrom" : "2007-06-27", "dateTo" : "2010-05-11"},
    {"title": "David Cameron I", "desc": "Coalition", "type" : "PM_SESSION", "dateFrom" : "2010-05-11", "dateTo" : "2015-05-08"},
    {"title": "David Cameron II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "2015-05-08", "dateTo" : "2016-07-13"},
    {"title": "Theresa May I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "2016-07-13", "dateTo" : "2017-07-11"},
    {"title": "Theresa May II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "2017-07-11", "dateTo" : "2019-09-24"},
    {"title": "Boris Johnson I", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "2019-09-24", "dateTo" : "2019-12-16"},
    {"title": "Boris Johnson II", "desc": "Conservative", "type" : "PM_SESSION", "dateFrom" : "2019-12-16", "dateTo" : "2022-01-05"}
]